#!/bin/bash

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  MERLin/Pods/SwiftFormat/CommandLineTool/swiftformat --config swiftformat.config "${line}";
  git add "$line";
done
