os: osx
language: objective-c
osx_image: xcode10.2.1
podfile: ./MERLin/Podfile
xcode_workspace: ./MERLin/MERLin.xcworkspace
xcode_scheme: MERLin
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X

before_install:
    - pod repo update

after_success:
    - bash <(curl -s https://codecov.io/bash)
