platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings! # supresses pods project warnings

def common
    pod 'LNZWeakCollection', '~>1.2.0'
    pod 'RxCocoa', '~>4.2.0'
end

target 'MERLin' do
    common
end

target 'MERLinTests' do
    common
    pod 'RxTest', '~>4.2.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxCocoa'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
