platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings! # supresses pods project warnings

def common
    pod 'LNZWeakCollection', '~>1.3.2'
    pod 'RxEnumKit', '~>1.0.1'
    pod 'SwiftFormat/CLI', '~>0.40.5'
end

target 'MERLin' do
    common
end

target 'MERLinTests' do
    common
    pod 'RxTest', '~>5.0.0'
end

post_install do |installer|
    # ensure git hooks are taken from the directory checked into git
    system("git config core.hooksPath .githooks")
end
