platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings! # supresses pods project warnings

abstract_target 'MERLinTargets' do
    pod 'MERLin', :path => '../'

    target 'MERLinSample'
    target 'RestaurantsListModule'
    target 'RestaurantDetailModule'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxCocoa'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
